name: Test
on:
  pull_request:
    paths: ['**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-go@5
        with:
          go-version: '1.22'
      - run: go test ./...
