name: Test
on:
  pull_request:
    paths: ['**/*.go']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
        go-version: '1.22'
      - name: Initialize go.mod (for CI only)
        run: |
          go mod init example.com/temp
          go mod tidy
      - run: go test ./\.go/excellent
